#version: '3.8'

services:
  api:
    container_name: node-ex01
    image: node:20.18.0
    working_dir: /app/nestjs
    env_file:
      - .env
#    environment:
#      - PORT=5000
    volumes:
      - './nest:/app/nestjs'
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - db
    command: ['npm', 'run', 'start:dev']

  db:
    container_name: f8-node-db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '4000:5432'
    volumes:
      - './db:/var/lib/postgresql/data'

volumes:
  db:
    driver: local

